import { Header } from "../components/Header";
import { CTAForm } from "../components/CTAForm";
import { FAQ } from "../components/FAQ";
import { MobileCTA } from "../components/MobileCTA";
import Image from "next/image";

const benefits = [["01", "Clear Marketing Direction", "Understand what you should focus on next."], ["02", "Customized AI Marketing Plan", "Get a practical plan designed specifically around your business."], ["03", "Find Your Growth Opportunities", "Identify areas where your current marketing can improve."], ["04", "Discover How AI Can Help", "Learn practical ways AI can support your marketing and save time."], ["05", "Know Your Next Steps", "Leave the consultation knowing exactly what to focus on next."]];
const steps = [["Tell Us About Your Business", "Fill out the short form and tell us about your business, current marketing, and goals."], ["Have a Free 1-to-1 Consultation", "Discuss your business and marketing challenges with us."], ["Get Your Customized AI Marketing Plan", "Receive a practical plan showing what you can focus on next and how AI-powered marketing can support your growth."]];
function ArrowButton({ children }: { children: React.ReactNode }) { return <a href="#consultation" className="button">{children}<span>→</span></a>; }
export default function Home() { return <main><Header />
  <section className="hero"><div className="hero-glow" /><div className="container hero-content"><p className="eyebrow hero-eyebrow">FREE AI MARKETING CONSULTATION FOR SMALL BUSINESSES</p><h1>Get a Free <mark>AI Marketing Plan</mark><br />to Attract More Customers</h1><p className="hero-lead">Discover what&apos;s holding your marketing back and get a practical AI-powered plan tailored to your business, customers, and goals.</p><ArrowButton>Get My Free AI Marketing Plan</ArrowButton><p className="microcopy">100% Free • Personalized for Your Business • No Obligation</p></div></section>
  <section className="problem section"><div className="container narrow"><p className="eyebrow">DOES THIS SOUND FAMILIAR?</p><h2>Is Your Marketing Getting Attention—<mark>but Not Enough Customers?</mark></h2><p className="intro">You may already be:</p><div className="chips">{["Posting on Facebook or Instagram", "Running advertisements", "Trying different offers", "Creating content", "Using different marketing tools"].map(x=><span key={x}>{x}</span>)}</div><p className="intro ask">But you may still be asking:</p><div className="questions">{["Why aren’t I getting enough customers?", "Where should I spend my marketing budget?", "What should I post?", "Are my ads actually working?", "How can I use AI for my business?", "What should I do next?"].map(x=><p key={x}>“{x}”</p>)}</div><div className="reassurance"><strong>You don&apos;t need to figure everything out alone.</strong><p>Get a customized AI Marketing Plan based on your business and current marketing situation.</p></div></div></section>
  <section className="audience section"><div className="container audience-wrap"><p className="eyebrow">WHO THIS IS FOR</p><h2>This Consultation Is For You If...</h2><div>{["You’re a small or growing business owner.", "You’re getting attention but not enough customers.", "You’re unsure where to spend your marketing budget.", "You’re struggling to create consistent content.", "You want to understand how AI can help your business.", "You want a clear marketing direction."].map((item) => <p key={item}><span>✓</span>{item}</p>)}</div></div></section>
  <section className="benefits section"><div className="container"><p className="eyebrow">WHAT YOU&apos;LL GET</p><h2>What You&apos;ll Get From the Free Consultation</h2><div className="benefit-grid">{benefits.map(([n,t,d])=><article className="benefit" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="process section"><div className="container"><p className="eyebrow">A SIMPLE PROCESS</p><h2>Clear direction starts here.</h2><div className="steps">{steps.map(([t,d],i)=><article key={t}><b>0{i+1}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
  <section className="sashi section"><div className="container sashi-wrap"><div className="sashi-photo"><Image src="/sashi-photo.png" alt="Sashi, AI Digital Marketing Expert" width={1122} height={1400} priority /></div><div><p className="eyebrow">A PERSONAL APPROACH</p><h2>Meet Sashi</h2><p>I&apos;m Sashi, an AI Digital Marketing Expert helping small businesses understand where to focus their marketing, attract more customers, and use AI to grow more efficiently.</p><ArrowButton>Get My Free AI Marketing Plan</ArrowButton></div></div></section>
  <section id="consultation" className="consultation section"><div className="container"><div className="consultation-intro"><p className="eyebrow">YOUR NEXT STEP</p><h2>Get the clarity your marketing needs.</h2><p>A personalized conversation about your business, your goals, and the practical opportunities in front of you.</p></div><CTAForm /></div></section>
  <FAQ />
  <section className="urgency"><div className="container"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Ready to Get Clearer About Your Marketing?</h2><p>Stop guessing what to do next. Get a personalized AI marketing plan based on your business, goals, and current marketing.</p><ArrowButton>Get My Free AI Marketing Plan</ArrowButton></div></section>
  <footer><strong>Consultation with Sashi</strong><span>AI Digital Marketing for Small Businesses</span><small>© {new Date().getFullYear()} Consultation with Sashi</small></footer><MobileCTA /></main>; }
