import { Header } from "../components/Header";
import { FlodeskForm } from "../components/FlodeskForm";
import { FAQ } from "../components/FAQ";
import { MobileCTA } from "../components/MobileCTA";
import Image from "next/image";

const benefits = [["01", "Marketing Review", "Identify what is working and where improvements are needed."], ["02", "AI Marketing Opportunities", "Discover practical ways AI can support your marketing."], ["03", "Lead Generation Ideas", "Get recommendations for attracting better-quality leads."], ["04", "Clear Action Plan", "Leave with practical next steps tailored to your business."]];
const steps = [["Tell Me About Your Business", "Complete the short consultation form."], ["Talk Directly with Sashi", "Discuss your business, current marketing challenges, and growth opportunities."], ["Get Practical Recommendations", "Receive clear AI and digital marketing recommendations for your business."]];
function ArrowButton({ children }: { children: React.ReactNode }) { return <a href="#consultation" className="button">{children}<span>→</span></a>; }
export default function Home() { return <main><Header />
  <section className="hero"><div className="hero-glow" /><div className="container hero-content"><p className="eyebrow hero-eyebrow">FREE AI MARKETING CONSULTATION FOR SMALL BUSINESSES</p><h1>Get a Free <mark>AI Marketing Plan</mark><br />to Attract More Customers</h1><p className="hero-lead">Get practical AI-powered marketing recommendations tailored to your business in a free 1-to-1 consultation with Sashi. Discover opportunities to attract more customers, generate leads, and improve your marketing strategy.</p><ArrowButton>Get My Free AI Marketing Plan</ArrowButton><p className="microcopy">Free 1-to-1 Consultation • No Obligation</p></div></section>
  <section className="problem section"><div className="container narrow"><p className="eyebrow">DOES THIS SOUND FAMILIAR?</p><h2>Is Your Marketing Getting Attention—<mark>but Not Enough Customers?</mark></h2><div className="chips">{["Posting regularly but getting little engagement", "Running ads without enough leads", "Unsure how to use AI effectively", "Spending too much time creating content", "No clear marketing strategy"].map(x=><span key={x}>{x}</span>)}</div><div className="reassurance"><strong>Your marketing does not need to be more complicated.</strong><p>It needs a clearer strategy.</p></div></div></section>
  <section className="benefits section"><div className="container"><p className="eyebrow">WHAT YOU&apos;LL GET</p><h2>What You&apos;ll Get From the Free Consultation</h2><div className="benefit-grid">{benefits.map(([n,t,d])=><article className="benefit" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="process section"><div className="container"><p className="eyebrow">A SIMPLE PROCESS</p><h2>Clear direction starts here.</h2><div className="steps">{steps.map(([t,d],i)=><article key={t}><b>0{i+1}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
  <section className="sashi section"><div className="container sashi-wrap"><div className="sashi-photo"><Image src="/sashi-photo.png" alt="Sashi, AI Digital Marketing Expert" width={1122} height={1400} quality={100} priority /></div><div><p className="eyebrow">AI MARKETING CONSULTANT</p><h2>Meet Sashi</h2><p>I&apos;m Sashi Shrestha, an AI marketing consultant focused on helping businesses use AI and digital marketing more strategically. My approach is practical and focused on identifying better marketing opportunities, improving lead generation, and creating a clearer path for growth.</p><p>The consultation focuses on your actual business situation rather than generic marketing advice.</p><ArrowButton>Get My Free AI Marketing Plan</ArrowButton></div></div></section>
  <section id="consultation" className="consultation section"><div className="container"><div className="consultation-intro"><p className="eyebrow">YOUR NEXT STEP</p><h2>Get the clarity your marketing needs.</h2><p>A personalized conversation about your business, your goals, and the practical opportunities in front of you.</p></div><div className="flodesk-card"><FlodeskForm /><p className="privacy">Your information will only be used regarding your consultation request.</p></div></div></section>
  <FAQ />
  <footer><strong>Consultation with Sashi</strong><span>AI Digital Marketing for Small Businesses</span><small>© {new Date().getFullYear()} Consultation with Sashi</small></footer><MobileCTA /></main>; }
